apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi-microservice
  type: NodePort
